import { execSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";

type Bucket = {
  id: string;
  title: string;
  matches: (filePath: string) => boolean;
};

const repoRoot = path.resolve(__dirname, "..");
const outputPath = path.join(repoRoot, "REPO_MAP.md");

const buckets: Bucket[] = [
  {
    id: "root",
    title: "Root governance + build/deploy manifests",
    matches: (filePath) => !filePath.includes("/"),
  },
  {
    id: "apps_web",
    title: "Workbench UI app (`apps/web`)",
    matches: (filePath) => filePath.startsWith("apps/web/"),
  },
  {
    id: "artifacts",
    title: "Governance fixtures (`artifacts`)",
    matches: (filePath) => filePath.startsWith("artifacts/"),
  },
  {
    id: "docs",
    title: "Ops/procurement docs (`docs`)",
    matches: (filePath) => filePath.startsWith("docs/"),
  },
  {
    id: "edge",
    title: "EDGE API subsystem (`edge`)",
    matches: (filePath) => filePath.startsWith("edge/"),
  },
  {
    id: "public",
    title: "Legacy/static demo web assets (`public`)",
    matches: (filePath) => filePath.startsWith("public/"),
  },
  {
    id: "scripts",
    title: "Automation/smoke/demo scripts (`scripts`)",
    matches: (filePath) => filePath.startsWith("scripts/"),
  },
  {
    id: "src",
    title: "Core deterministic API runtime (`src`)",
    matches: (filePath) => filePath.startsWith("src/"),
  },
  {
    id: "tests",
    title: "Decision-table test fixtures (`tests`)",
    matches: (filePath) => filePath.startsWith("tests/"),
  },
];

const knownLocalStatePaths = [
  ".git",
  ".pnpm-store",
  ".vscode",
  ".DS_Store",
  "node_modules",
  "dist",
  "runs",
  "apps/web/.next",
  "apps/web/out",
  "apps/web/node_modules",
];

const run = (command: string): string =>
  execSync(command, { cwd: repoRoot, encoding: "utf8" }).trim();

const trackedFiles = run("git ls-files")
  .split("\n")
  .map((line) => line.trim())
  .filter(Boolean)
  .sort((a, b) => a.localeCompare(b));

const generatedAt =
  run("git log -1 --format=%cI") || new Date().toISOString();

const filesByBucket = new Map<string, string[]>();
for (const bucket of buckets) {
  filesByBucket.set(bucket.id, []);
}

const unclassified: string[] = [];
for (const filePath of trackedFiles) {
  const bucket = buckets.find((item) => item.matches(filePath));
  if (!bucket) {
    unclassified.push(filePath);
    continue;
  }
  const list = filesByBucket.get(bucket.id);
  if (!list) {
    throw new Error(`Internal error: missing bucket storage for ${bucket.id}`);
  }
  list.push(filePath);
}

if (unclassified.length > 0) {
  throw new Error(
    `Unclassified tracked file(s):\n${unclassified.map((value) => `- ${value}`).join("\n")}`,
  );
}

const counts = buckets.map((bucket) => {
  const files = filesByBucket.get(bucket.id) ?? [];
  return { bucket, count: files.length };
});

const totalCount = counts.reduce((sum, item) => sum + item.count, 0);
if (totalCount !== trackedFiles.length) {
  throw new Error(
    `Count mismatch: buckets=${totalCount}, tracked=${trackedFiles.length}`,
  );
}

const coverageEquation =
  counts.map((item) => String(item.count)).join(" + ") + ` = ${totalCount}`;

const localStatePresent = knownLocalStatePaths.filter((value) =>
  existsSync(path.join(repoRoot, value)),
);

const lines: string[] = [];

lines.push("# REPO_MAP");
lines.push("");
lines.push("_This file is auto-generated by `scripts/generateRepoMap.ts`. Do not edit manually._");
lines.push("");
lines.push("## Metadata");
lines.push(`- generated_at_utc: \`${generatedAt}\``);
lines.push("- scope: `git ls-files` (tracked files only)");
lines.push("- refresh: `pnpm exec ts-node scripts/generateRepoMap.ts`");
lines.push("");
lines.push("## MECE Summary");
lines.push(`Tracked files: **${totalCount}**`);
lines.push(`Coverage equation: \`${coverageEquation}\``);
lines.push("");

counts.forEach((item, index) => {
  lines.push(`${index + 1}. ${item.bucket.title} (${item.count})`);
});

lines.push("");
lines.push("## Full Inventory");
lines.push("");

counts.forEach((item, index) => {
  const files = filesByBucket.get(item.bucket.id) ?? [];
  lines.push(`### ${index + 1}) ${item.bucket.title} (${files.length})`);
  lines.push("```text");
  files.forEach((value) => {
    lines.push(value);
  });
  lines.push("```");
  lines.push("");
});

if (localStatePresent.length > 0) {
  lines.push("## Local-State Notes (excluded from tracked counts)");
  lines.push(
    "The following local/generated paths are present in this workspace but excluded from tracked MECE totals:",
  );
  localStatePresent.forEach((value) => {
    lines.push(`- \`${value}\``);
  });
  lines.push("");
}

writeFileSync(outputPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote ${outputPath} (${totalCount} tracked files)`);
